### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mistik911** [Twinkiee/TwinkiePlates#1] opened 2015-09-13 16:37 UTC
I found a weird bug with TwinkiePlates. When you see a nameplate in the distance it says one value for health and shields, then when you click on them it shows the actual health and shield value. Like in the pictures below:

This picture shows what you see without clicking on a Player, NPC, Object, etc...

![rockem_sockem 150913 104610](https://cloud.githubusercontent.com/assets/9784191/9837646/23ee49a4-5a14-11e5-8755-b845e6f24981.png)

This one shows what happens when you actually click on Player, NPC, Object, etc...

![rockem_sockem 150913 104616](https://cloud.githubusercontent.com/assets/9784191/9837649/34c83eb0-5a14-11e5-8b27-15e86fc80c05.png)

Thanks for the help and keeping this awesome addon updated!

**Comment by mistik911** [comment] 2015-09-13 17:59
Update 1: Seems to be something with the options to hide the health bar and shield bar at full.

**Comment by Twinkiee** [comment] 2015-09-14 13:08
Hi mistik911,
thank you for your report. I noticed this bug as well and yet I have to determine the root cause of it.
Can you please provide me a screenshot of your configuration matrix?

Thanks,
Twinkie,

**Comment by mistik911** [comment] 2015-09-15 22:30
Heres what I have enabled in the options:

![rockem_sockem 150915 182654](https://cloud.githubusercontent.com/assets/9784191/9891898/db8dfcb6-5bd7-11e5-9b4e-2dfadcb230a7.png)

**Comment by Twinkiee** [comment] 2015-09-15 22:45
Thank you, gonna check it out asap.

**Comment by Twinkiee** [comment] 2015-12-28 14:22
Should be fixed in v1.4.7

**Closed as completed by Twinkiee** 2015-12-28 14:22 UTC
Labels: bug
